# --------------------------------------------------------------------------------
# This file is not part of the solution, it will tell cargo where to look for the 
# different configurations during cross compilation.
#
# It needs to be copied to ~/.cargo/config:
# Command: 'cp cargo-config.toml ~/.cargo/config'
#
# Afterwards to use 'rustup' and add all these targets we can use them during 
# cross compilation:
# 
# ANDROID add targets: 
# 'rustup target add armv7-linux-androideabi aarch64-linux-android 
# i686-linux-android x86_64-linux-android'

# ANDROID build targets from 'cryptor-jni' directory: 
# 'cargo build --target armv7-linux-androideabi --release'
# 'cargo build --target aarch64-linux-android --release'
# 'cargo build --target i686-linux-android --release'
# 'cargo build --target x86_64-linux-android --release'
# --------------------------------------------------------------------------------


# --------------------------------------------------------------------------------
# ANDROID TARGETS 
# https://developer.android.com/ndk/guides/other_build_systems
# https://developer.android.com/ndk/guides/abis
# --------------------------------------------------------------------------------

[target.armv7-linux-androideabi]
ar = "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar"
linker = "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang"

[target.aarch64-linux-android]
ar = "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar"
linker = "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang"

[target.i686-linux-android]
ar = "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-ar"
linker = "ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android21-clang"

[target.x86_64-linux-android]
ar = "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-ar"
linker = "ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang"